name: "comprehensive-test-project"
description: "A comprehensive test project with all components enabled"
license: "MIT"
organization: "test-org"
author: "Test Author"
email: "test@test-org.com"
repository: "https://github.com/test-org/comprehensive-test-project"
output_path: "./output/comprehensive-test"

components:
  frontend:
    main_app: true
    home: true
    admin: true
  backend:
    api: true
  mobile:
    android: true
    ios: true
  infrastructure:
    docker: true
    kubernetes: true
    terraform: true

versions:
  node: "20.11.0"
  go: "1.24.0"
  nextjs: "15.0.0"
  react: "19.0.0"
  kotlin: "2.0.0"
  swift: "5.9.0"