name: Bug Report
description: File a bug report to help us improve
title: "[BUG]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: template-type
    attributes:
      label: Template Type
      description: Which template were you using when the bug occurred?
      options:
        - Go/Gin Backend
        - Next.js App
        - Next.js Admin
        - Next.js Landing Page
        - Android (Kotlin)
        - iOS (Swift)
        - Docker/Kubernetes
        - Terraform
        - Custom Template
        - Not applicable
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Mode
      description: Which mode were you using?
      options:
        - Interactive
        - Non-interactive (CLI flags)
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command Used
      description: The exact CLI command you ran
      placeholder: |
        e.g., ospg generate --template go-gin --name myproject
      render: shell
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g. Ubuntu 20.04, macOS 12.0, Windows 10]
        - Go Version: [e.g. 1.25.0]
        - Generator Version: [e.g. 1.4.0]
        - Shell: [e.g. bash, zsh, PowerShell]
    validations:
      required: true

  - type: checkboxes
    id: validation
    attributes:
      label: Project Validation
      description: Did you run validation on the generated project?
      options:
        - label: I ran validation and it passed
        - label: I ran validation and it failed
        - label: I did not run validation

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: If applicable, add logs or error messages to help explain your problem.
      placeholder: Paste any relevant logs or error messages here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
