name: Bug Report
description: File a bug report to help us improve
title: "[BUG]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this bug! Please provide details to help us reproduce and fix the issue.

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Run command: ...
        2. See error: ...
    validations:
      required: true

  - type: dropdown
    id: template-type
    attributes:
      label: Template Type
      description: Which template were you using when the bug occurred?
      options:
        - Go/Gin Backend
        - Next.js App
        - Next.js Admin
        - Next.js Landing Page
        - Android (Kotlin)
        - iOS (Swift)
        - Docker/Kubernetes
        - Terraform
        - Custom Template
        - Not applicable
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Mode
      description: Which mode were you using?
      options:
        - Interactive
        - Non-interactive (CLI flags)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Generator Version
      description: Run `generator version` to get this
      placeholder: "1.4.0"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        OS: Ubuntu 20.04
        Go: 1.25.0
        Shell: bash
      render: shell
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command Used
      placeholder: "generator generate --template go-gin --name myproject"
      render: shell
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Output
      placeholder: Paste error messages or relevant output...
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I've searched existing issues
          required: true
        - label: I agree to follow the Code of Conduct
          required: true
