blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/cuesoftinc/open-source-project-generator/tree/main/docs
    about: Check our documentation for detailed guides and references.
  - name: Security Issues
    url: https://github.com/cuesoftinc/open-source-project-generator/security/advisories/new
    about: Report security vulnerabilities privately.
