name: Question
description: Ask a question about the project
title: "[QUESTION]: "
labels: ["question", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please check the docs first, then provide details below.

  - type: dropdown
    id: question-category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation & Setup
        - Usage & Commands
        - Templates & Customization
        - Configuration
        - Validation & Security
        - CI/CD Integration
        - Troubleshooting
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      placeholder: |
        What I'm trying to do: ...
        What I've tried: ...
        Environment (if relevant): OS, Go version, Generator version

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I've checked the documentation
          required: true
        - label: I've searched existing issues
          required: true
        - label: I agree to follow the Code of Conduct
          required: true
