name: Security Vulnerability
description: Report a security vulnerability
title: "[SECURITY]: "
labels: ["security", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **⚠️ IMPORTANT: For critical vulnerabilities, use private reporting!**

        For critical security issues, report privately at:
        https://github.com/cuesoftinc/open-source-project-generator/security/advisories/new

        Or email: support@cuesoft.io

        This public template is for security-related discussions, hardening suggestions, or low-severity issues only.

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      options:
        - Code/Command Injection
        - Path Traversal
        - Information Disclosure
        - Denial of Service
        - Dependency Vulnerability
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description & Impact
      placeholder: |
        What: ...
        Impact: ...
        Environment: OS, Go version, Generator version
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction Steps
      placeholder: |
        1. ...
        2. ...
      render: shell
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Details
      placeholder: PoC code, CVE/CWE references, etc.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Responsible Disclosure Agreement
      description: By submitting this report, you agree to responsible disclosure practices
      options:
        - label: I agree to responsible disclosure practices and will not publicly disclose this vulnerability until it has been patched
          required: true
