name: Security Vulnerability
description: Report a security vulnerability
title: "[SECURITY]: "
labels: ["security", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT**: Please do not report security vulnerabilities through public GitHub issues. Instead, please follow our responsible disclosure process.

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security vulnerability is this?
      options:
        - Code Injection
        - Path Traversal
        - Command Injection
        - Cross-Site Scripting (XSS)
        - Insecure Deserialization
        - Authentication/Authorization
        - Information Disclosure
        - Denial of Service
        - Dependency Vulnerability
        - Other
    validations:
      required: true

  - type: checkboxes
    id: affected-components
    attributes:
      label: Affected Components
      description: Which components are affected by this vulnerability?
      options:
        - label: Template Processing Engine
        - label: File System Operations
        - label: CLI Input Handling
        - label: Configuration Parser
        - label: Validation System
        - label: Cache System
        - label: Security Module
        - label: Dependencies

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: A clear and concise description of the security vulnerability.
      placeholder: Describe the security issue...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe the potential impact of this vulnerability
      placeholder: What could an attacker do with this vulnerability?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be reproduced?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See vulnerability
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g. Ubuntu 20.04, macOS 12.0, Windows 10]
        - Go Version: [e.g. 1.25.0]
        - Generator Version: [e.g. 1.4.0]
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this vulnerability?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept
      description: Provide a proof of concept or exploit code (if applicable)
      placeholder: |
        Provide minimal code or steps that demonstrate the vulnerability.
        Please be responsible and avoid including actual exploits.
      render: shell

  - type: textarea
    id: cve-cwe-reference
    attributes:
      label: CVE/CWE Reference (Optional)
      description: If this matches a known vulnerability pattern, provide the CVE or CWE identifier
      placeholder: |
        - CVE: CVE-XXXX-XXXXX
        - CWE: CWE-XXX

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the vulnerability here.
      placeholder: Any additional information that might be helpful...

  - type: markdown
    attributes:
      value: |
        ## Responsible Disclosure

        **Please do not create a public issue for security vulnerabilities.**

        Instead, please:

        1. **Use GitHub Security Advisories** at https://github.com/cuesoftinc/open-source-project-generator/security/advisories/new
        2. **Email us directly** at support@cuesoft.io
        3. **Contact maintainers privately** through other secure channels

        We will:
        - Acknowledge receipt within 48 hours
        - Provide regular updates on our progress
        - Credit you in our security advisories (if desired)
        - Work with you to coordinate disclosure

        Thank you for helping keep our project secure!

  - type: checkboxes
    id: terms
    attributes:
      label: Responsible Disclosure Agreement
      description: By submitting this report, you agree to responsible disclosure practices
      options:
        - label: I agree to responsible disclosure practices and will not publicly disclose this vulnerability until it has been patched
          required: true
