# Mobile-Focused Configuration Example
# For mobile applications with backend API

name: "mobile-app"
organization: "mobile-team"
description: "Cross-platform mobile application with Go backend"
license: "Apache-2.0"
author: "Mobile Developer"
email: "dev@mobile-team.com"
output_path: "output/mobile"

components:
  frontend:
    nextjs:
      app: false    # No web frontend
      home: false
      admin: false
      shared: false
  backend:
    go_gin: true    # API backend for mobile apps
  mobile:
    android: true   # Android application
    ios: true       # iOS application
  infrastructure:
    docker: true    # For backend deployment
    kubernetes: true # For scalable backend
    terraform: false

versions:
  go: "1.22.0"
  packages:
    "kotlin": "2.0.0"
    "swift": "5.9.0"
    "android-gradle-plugin": "8.2.0"
    "gin-gonic/gin": "v1.9.1"
    "golang-jwt/jwt": "v5.0.0"