# Enterprise Configuration Example
# Full-scale enterprise application with all components and infrastructure

name: "enterprise-platform"
organization: "enterprise-corp"
description: "Enterprise-grade platform with web, mobile, and comprehensive infrastructure"
license: "Apache-2.0"
author: "Enterprise Development Team"
email: "platform@enterprise-corp.com"
repository: "https://github.com/enterprise-corp/enterprise-platform"
output_path: "output/enterprise"

# Enable all components for enterprise deployment
components:
  frontend:
    nextjs:
      app: true     # Main web application
      home: true    # Public landing page
      admin: true   # Administrative dashboard
      shared: true  # Shared component library
  backend:
    go_gin: true    # High-performance API backend
  mobile:
    android: true   # Android mobile app
    ios: true       # iOS mobile app
  infrastructure:
    docker: true      # Containerization
    kubernetes: true  # Orchestration
    terraform: true   # Infrastructure as Code

# Enterprise-grade versions with stability focus
versions:
  node: "20.11.0"  # LTS version
  go: "1.22.0"     # Latest stable
  packages:
    # Frontend - Production-ready versions
    "react": "18.2.0"
    "next": "15.0.0"
    "typescript": "5.3.0"
    "tailwindcss": "3.4.0"
    "eslint": "8.56.0"
    "prettier": "3.2.0"
    "@types/react": "18.2.0"
    "@types/node": "20.11.0"
    
    # Backend - Enterprise security and performance
    "gin-gonic/gin": "v1.9.1"
    "golang-jwt/jwt": "v5.0.0"
    "go-playground/validator": "v10.16.0"
    "gorm.io/gorm": "v1.25.0"
    "go-redis/redis": "v9.3.0"
    
    # Mobile - Latest stable versions
    "kotlin": "2.0.0"
    "swift": "5.9.0"
    "android-gradle-plugin": "8.2.0"
    
    # Infrastructure - Production-ready tools
    "docker": "24.0.0"
    "kubernetes": "1.29.0"
    "terraform": "1.6.0"
    "helm": "3.13.0"
    "prometheus": "2.48.0"
    "grafana": "10.2.0"