# Frontend-Only Configuration Example
# Perfect for frontend applications or static sites

name: "frontend-app"
organization: "frontend-team"
description: "A modern frontend application with multiple entry points"
license: "MIT"
author: "Frontend Developer"
email: "dev@frontend-team.com"
output_path: "output/frontend"

components:
  frontend:
    nextjs:
      app: true     # Main application
      home: true    # Landing page
      admin: true   # Admin dashboard
      shared: true  # Shared components
  backend:
    go_gin: false   # No backend needed
  mobile:
    android: false
    ios: false
  infrastructure:
    docker: true    # For containerized deployment
    kubernetes: false
    terraform: false

versions:
  node: "20.11.0"
  packages:
    "react": "18.2.0"
    "next": "15.0.0"
    "typescript": "5.3.0"
    "tailwindcss": "3.4.0"
    "eslint": "8.56.0"