# Example Project Configuration
# This file demonstrates the configuration format for the Open Source Project Generator

name: example-fullstack-app
description: A full-stack application with Next.js frontend and Go backend
output_dir: ./example-fullstack-app

components:
  # Frontend - Next.js web application
  - type: nextjs
    name: web-app
    enabled: true
    config:
      name: web-app
      typescript: true
      tailwind: true
      app_router: true
      eslint: true

  # Backend - Go API server with Gin
  - type: go-backend
    name: api-server
    enabled: true
    config:
      name: api-server
      module: github.com/example/fullstack-app
      framework: gin
      port: 8080

  # Mobile - Android app (disabled by default)
  - type: android
    name: mobile-android
    enabled: false
    config:
      name: mobile-android
      package: com.example.fullstackapp
      min_sdk: 24
      target_sdk: 34
      language: kotlin

  # Mobile - iOS app (disabled by default)
  - type: ios
    name: mobile-ios
    enabled: false
    config:
      name: mobile-ios
      bundle_id: com.example.fullstackapp
      deployment_target: "15.0"
      language: swift

# Integration configuration
integration:
  generate_docker_compose: true
  generate_scripts: true
  api_endpoints:
    backend: http://localhost:8080
    frontend: http://localhost:3000
  shared_environment:
    NODE_ENV: development
    LOG_LEVEL: info
    API_TIMEOUT: "30"

# Generation options
options:
  use_external_tools: true
  dry_run: false
  verbose: false
  create_backup: true
  force_overwrite: false
