# Frontend-Only Configuration
# This example generates a Next.js frontend application without backend

name: "frontend-app"
description: "Frontend-only Next.js application"
output_dir: "./frontend-app"

# Components to generate
components:
  # Next.js Frontend Application
  - type: nextjs
    name: web-app
    enabled: true
    config:
      name: web-app
      typescript: true
      tailwind: true
      app_router: true
      eslint: true
      src_dir: true          # Use src/ directory
      import_alias: "@/*"    # Import alias for src/

  # Docker Configuration (optional for frontend)
  - type: docker
    name: docker-config
    enabled: false
    config:
      compose_version: "3.8"
      include_dev: true
      nginx: true            # Include Nginx for production

# Integration settings
integration:
  generate_docker_compose: true
  generate_scripts: true
  
  # External API configuration
  api_endpoints:
    backend: https://api.example.com
  
  # Environment configuration
  environment:
    NEXT_PUBLIC_API_URL: https://api.example.com
    NEXT_PUBLIC_APP_NAME: "Frontend App"
    NEXT_PUBLIC_ENV: production

# Generation options
options:
  use_external_tools: true
  dry_run: false
  verbose: false
  create_backup: true
  update_versions: true
