# Minimal Project Configuration
# Bare minimum configuration for quick project generation
#
# This is the simplest possible configuration with only required fields.
# All optional settings will use their default values.
#
# Usage:
#   project-generator generate --config configs/minimal.yaml

# Required fields only
name: minimal-project
output_dir: ./minimal-project

# At least one component must be enabled
components:
  - type: nextjs
    name: web-app
    enabled: true
    config:
      name: web-app

# All other settings will use defaults:
# - integration.generate_docker_compose: false
# - integration.generate_scripts: false
# - options.use_external_tools: true
# - options.dry_run: false
# - options.verbose: false
# - options.create_backup: true
# - options.force_overwrite: false
