# Mobile-Only Project Configuration
# Example configuration for mobile applications (Android and iOS)
#
# This configuration generates native mobile applications without web frontend or backend.
# Ideal for:
# - Mobile apps connecting to existing APIs
# - Cross-platform mobile development
# - Mobile-first applications
# - Native mobile experiences
#
# Usage:
#   project-generator generate --config configs/mobile-only.yaml

# Project metadata
name: mobile-app
description: Native mobile applications for Android and iOS
output_dir: ./mobile-app

# Component definitions
components:
  # Frontend - Disabled for mobile-only project
  - type: nextjs
    name: web-app
    enabled: false
    config:
      name: web-app
      typescript: true
      tailwind: true
      app_router: true
      eslint: true

  # Backend - Disabled for mobile-only project
  - type: go-backend
    name: api-server
    enabled: false
    config:
      name: api-server
      module: github.com/example/mobile-app
      framework: gin
      port: 8080

  # Mobile - Android application
  - type: android
    name: mobile-android
    enabled: true
    config:
      name: mobile-android
      package: com.example.mobileapp     # Android package name
      min_sdk: 24                        # Android 7.0 (Nougat)
      target_sdk: 34                     # Android 14
      language: kotlin                   # Kotlin programming language

  # Mobile - iOS application
  - type: ios
    name: mobile-ios
    enabled: true
    config:
      name: mobile-ios
      bundle_id: com.example.mobileapp   # iOS bundle identifier
      deployment_target: "15.0"          # iOS 15.0 minimum
      language: swift                    # Swift programming language

# Integration configuration
integration:
  # Docker Compose not needed for mobile-only
  generate_docker_compose: false
  
  # Generate build scripts for mobile platforms
  generate_scripts: true
  
  # API endpoint configuration (external API)
  api_endpoints:
    backend: https://api.example.com     # External API endpoint
  
  # Shared environment variables for mobile apps
  shared_environment:
    # API configuration
    API_BASE_URL: https://api.example.com
    API_TIMEOUT: "30"
    API_VERSION: v1
    
    # App configuration
    APP_NAME: "Mobile App"
    APP_VERSION: "1.0.0"
    
    # Feature flags
    ENABLE_ANALYTICS: "true"
    ENABLE_CRASH_REPORTING: "true"
    ENABLE_PUSH_NOTIFICATIONS: "true"
    
    # Environment
    ENVIRONMENT: development

# Generation options
options:
  # Use external tools when available (gradle, xcodebuild)
  # Falls back to minimal template generation if tools not found
  use_external_tools: true
  
  # Preview mode
  dry_run: false
  
  # Verbose output
  verbose: false
  
  # Backup existing files
  create_backup: true
  
  # Prompt before overwriting
  force_overwrite: false
