# Comprehensive Test Configuration
# This file includes all possible configuration options for testing purposes

# Basic project information
name: "comprehensive-test-project"
organization: "test-organization"
description: "A comprehensive test project that includes all possible configuration options for testing the project generator"
license: "MIT"
author: "Test Author"
email: "test.author@example.com"
repository: "https://github.com/test-organization/comprehensive-test-project"

# Output configuration
output_path: "output/generated"

# Features list for testing
features:
  - "authentication"
  - "authorization"
  - "api-documentation"
  - "testing-framework"
  - "logging"
  - "monitoring"
  - "caching"
  - "database-migrations"
  - "file-upload"
  - "email-notifications"
  - "websockets"
  - "background-jobs"
  - "rate-limiting"
  - "internationalization"
  - "search-functionality"

# Component selection - all components enabled
components:
  # Frontend components
  frontend:
    nextjs:
      app: true
      home: true
      admin: true
      shared: true

  # Backend components
  backend:
    go_gin: true

  # Mobile components
  mobile:
    android: true
    ios: true
    shared: true

  # Infrastructure components
  infrastructure:
    docker: true
    kubernetes: true
    terraform: true

  # Database components
  database:
    postgresql: true
    mysql: true
    mongodb: true
    sqlite: true

  # Cache components
  cache:
    redis: true
    memcached: true

  # DevOps components
  devops:
    cicd: true
    github_actions: true
    gitlab_ci: true
    jenkins: true

  # Monitoring components
  monitoring:
    prometheus: true
    grafana: true
    jaeger: true
    elk: true

# Version configuration
versions:
  # Language versions
  node: "20.11.0"
  go: "1.25.0"

  # Package versions
  packages:
    # Frontend packages
    "next": "14.0.4"
    "react": "18.2.0"
    "typescript": "^5.3.0"
    "@types/react": "^18.2.0"
    "@types/node": "^20.0.0"
    "tailwindcss": "^3.3.0"
    "eslint": "^8.0.0"
    "prettier": "^3.0.0"

    # Backend packages (Go modules)
    "github.com/gin-gonic/gin": "v1.9.1"
    "github.com/golang-jwt/jwt/v5": "v5.0.0"
    "gorm.io/gorm": "v1.25.5"
    "gorm.io/driver/postgres": "v1.5.4"
    "gorm.io/driver/mysql": "v1.5.2"
    "go.mongodb.org/mongo-driver": "v1.12.1"
    "github.com/redis/go-redis/v9": "v9.3.0"

    # Testing packages
    "github.com/stretchr/testify": "v1.8.4"
    "github.com/onsi/ginkgo/v2": "v2.13.0"
    "github.com/onsi/gomega": "v1.30.0"

    # DevOps and monitoring
    "github.com/prometheus/client_golang": "v1.17.0"
    "go.opentelemetry.io/otel": "v1.21.0"
    "github.com/sirupsen/logrus": "v1.9.3"

    # Mobile development
    "react-native": "0.72.6"
    "@react-native-community/cli": "^12.0.0"
    "expo": "~49.0.0"

    # Infrastructure
    "terraform": "1.6.0"
    "kubernetes": "1.28.0"
    "docker": "24.0.0"

# Generation metadata (will be populated automatically)
generated_at: "2024-01-01T00:00:00Z"
generator_version: "1.0.0"
