# Centralized Version Configuration
# This file is the single source of truth for all dependency versions
# Update this file and run `make check-versions` to verify and propagate changes

# Frontend Dependencies
frontend:
  nextjs:
    version: "16.0.0"
    package: "create-next-app"
  react:
    version: "19.2.0"
  react_dom:
    version: "19.2.0"
  typescript:
    version: "5.9.3"
# Backend Dependencies
backend:
  go:
    version: "1.25.0"
    docker_tag: "1.25-alpine"
  frameworks:
    gin:
      version: "v1.11.0"
      package: "github.com/gin-gonic/gin"
    gin_cors:
      version: "v1.7.6"
      package: "github.com/gin-contrib/cors"
    echo:
      version: "v4.13.4"
      package: "github.com/labstack/echo/v4"
    fiber:
      version: "v2.52.9"
      package: "github.com/gofiber/fiber/v2"
# Android Dependencies
android:
  compile_sdk: "36"
  min_sdk: "24"
  target_sdk: "36"
  java_version: "17"
  kotlin:
    version: "v2.2.21"
  gradle:
    version: "9.1.0"
    distribution_url: "https://services.gradle.org/distributions/gradle-9.1.0-bin.zip"
  gradle_plugin:
    version: "8.13.0"
  androidx:
    core_ktx:
      version: "1.17.0"
      package: "androidx.core:core-ktx"
    appcompat:
      version: "1.7.1"
      package: "androidx.appcompat:appcompat"
    material:
      version: "1.13.0"
      package: "com.google.android.material:material"
    constraintlayout:
      version: "2.2.1"
      package: "androidx.constraintlayout:constraintlayout"
  testing:
    junit:
      version: "4.13.2"
      package: "junit:junit"
    androidx_junit:
      version: "1.3.0"
      package: "androidx.test.ext:junit"
    espresso:
      version: "3.7.0"
      package: "androidx.test.espresso:espresso-core"
# iOS Dependencies
ios:
  swift:
    version: "swift-6.2-RELEASE"
    short_version: "6.2"
  xcode:
    version: "26.0.1"
  deployment_target: "26.0"
# Docker Base Images
docker:
  alpine:
    version: "3.22"
  golang:
    version: "1.25-alpine"
  ubuntu:
    version: "25.10"
# Infrastructure Tools
infrastructure:
  terraform:
    version: "v1.13.4"
  kubernetes:
    version: "v1.34.1"
# Metadata
metadata:
  last_updated: "2025-10-24"
  schema_version: "1.0.0"
