name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., v1.0.0)"
        required: true
        type: string

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  packages: write

env:
  GO_VERSION: "1.25"

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: linux
            arch: 386
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: windows
            arch: amd64
          - os: windows
            arch: 386

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Set build variables
        id: vars
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          GIT_COMMIT=$(git rev-parse --short HEAD)
          BUILD_TIME=$(date -u '+%Y-%m-%d_%H:%M:%S')

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "git_commit=${GIT_COMMIT}" >> $GITHUB_OUTPUT
          echo "build_time=${BUILD_TIME}" >> $GITHUB_OUTPUT

          # Set binary extension for Windows
          if [ "${{ matrix.os }}" = "windows" ]; then
            echo "binary_ext=.exe" >> $GITHUB_OUTPUT
          else
            echo "binary_ext=" >> $GITHUB_OUTPUT
          fi

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
          VERSION: ${{ steps.vars.outputs.version }}
          GIT_COMMIT: ${{ steps.vars.outputs.git_commit }}
          BUILD_TIME: ${{ steps.vars.outputs.build_time }}
        run: |
          LDFLAGS="-X main.Version=${VERSION} -X main.GitCommit=${GIT_COMMIT} -X main.BuildTime=${BUILD_TIME} -s -w"

          mkdir -p dist/generator-${{ matrix.os }}-${{ matrix.arch }}

          go build -ldflags "${LDFLAGS}" -trimpath -o "dist/generator-${{ matrix.os }}-${{ matrix.arch }}/generator${{ steps.vars.outputs.binary_ext }}" ./cmd/generator

          # Copy additional files
          cp README.md "dist/generator-${{ matrix.os }}-${{ matrix.arch }}/"
          if [ -f LICENSE ]; then
            cp LICENSE "dist/generator-${{ matrix.os }}-${{ matrix.arch }}/"
          fi

          # Create installation instructions
          case "${{ matrix.os }}" in
            "windows")
              cat > "dist/generator-${{ matrix.os }}-${{ matrix.arch }}/INSTALL.txt" << 'EOF'
          Installation Instructions for Windows
          ====================================

          1. Extract the archive to a directory (e.g., C:\Program Files\generator)
          2. Add the directory to your PATH environment variable:
             - Open System Properties > Advanced > Environment Variables
             - Edit the PATH variable and add the generator directory
             - Or run: setx PATH "%PATH%;C:\Program Files\generator"
          3. Open a new command prompt and run: generator --help

          Alternative: Place generator.exe in any directory that's already in your PATH.
          EOF
              ;;
            "darwin")
              cat > "dist/generator-${{ matrix.os }}-${{ matrix.arch }}/INSTALL.txt" << 'EOF'
          Installation Instructions for macOS
          ==================================

          Option 1: Manual Installation
          1. Extract the archive to a directory (e.g., /usr/local/bin)
          2. Make the binary executable: chmod +x generator
          3. Ensure the directory is in your PATH
          4. Run: generator --help

          Option 2: Using Homebrew (if available)
          1. Move generator to /usr/local/bin/
          2. Run: generator --help

          Option 3: User Installation
          1. Create ~/bin directory: mkdir -p ~/bin
          2. Move generator to ~/bin/
          3. Add to PATH: echo 'export PATH="$HOME/bin:$PATH"' >> ~/.zshrc
          4. Reload shell: source ~/.zshrc
          5. Run: generator --help
          EOF
              ;;
            *)
              cat > "dist/generator-${{ matrix.os }}-${{ matrix.arch }}/INSTALL.txt" << 'EOF'
          Installation Instructions for Linux
          ==================================

          Option 1: System-wide Installation (requires sudo)
          1. Extract the archive
          2. Copy to system directory: sudo cp generator /usr/local/bin/
          3. Make executable: sudo chmod +x /usr/local/bin/generator
          4. Run: generator --help

          Option 2: User Installation
          1. Create ~/bin directory: mkdir -p ~/bin
          2. Copy generator to ~/bin/
          3. Make executable: chmod +x ~/bin/generator
          4. Add to PATH: echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
          5. Reload shell: source ~/.bashrc
          6. Run: generator --help
          EOF
              ;;
          esac

      - name: Create and upload Windows archive
        if: matrix.os == 'windows'
        run: |
          cd dist
          zip -r "generator-${{ matrix.os }}-${{ matrix.arch }}.zip" "generator-${{ matrix.os }}-${{ matrix.arch }}/"

      - name: Upload Windows artifacts
        if: matrix.os == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: generator-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/generator-${{ matrix.os }}-${{ matrix.arch }}.zip
          retention-days: 7

      - name: Create and upload non-Windows archive
        if: matrix.os != 'windows'
        run: |
          cd dist
          tar -czf "generator-${{ matrix.os }}-${{ matrix.arch }}.tar.gz" "generator-${{ matrix.os }}-${{ matrix.arch }}/"

      - name: Upload non-Windows artifacts
        if: matrix.os != 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: generator-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/generator-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          retention-days: 7

  package:
    name: Build Packages
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download Linux AMD64 artifact
        uses: actions/download-artifact@v6
        with:
          name: generator-linux-amd64
          path: dist/

      - name: Extract Linux binary
        run: |
          cd dist
          echo "Files in dist directory:"
          ls -la
          tar -xzf generator-linux-amd64.tar.gz

      - name: Install packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm build-essential

      - name: Get version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Build packages
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: make package

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages/
          retention-days: 7

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build, package]
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Download binary artifacts
        uses: actions/download-artifact@v6
        with:
          path: artifacts/
          pattern: generator-*
          merge-multiple: true

      - name: Download package artifacts
        uses: actions/download-artifact@v6
        with:
          path: artifacts/
          name: packages

      - name: Prepare release assets
        run: |
          mkdir -p release-assets

          # Copy binary archives
          find artifacts/ -name "*.tar.gz" -o -name "*.zip" | while read file; do
            cp "$file" release-assets/
          done

          # Copy packages
          find artifacts/packages/ -name "*.deb" -o -name "*.rpm" | while read file; do
            cp "$file" release-assets/
          done

      - name: Generate checksums
        run: |
          cd release-assets
          sha256sum * > checksums.txt

      - name: Generate release notes
        id: release_notes
        run: |
          # Extract changelog entry for this version
          VERSION="${{ steps.version.outputs.version }}"

          # Get the changelog section for this version
          CHANGELOG_SECTION=$(awk "/^## \[$VERSION\]/{flag=1; next} /^## \[/{flag=0} flag" CHANGELOG.md)

          # If no specific version found, get the latest unreleased changes
          if [ -z "$CHANGELOG_SECTION" ]; then
            CHANGELOG_SECTION=$(awk '/^## \[/{if(found) exit; found=1; next} found' CHANGELOG.md)
          fi

          # Get commit messages since last tag for additional context
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -n "$LAST_TAG" ]; then
            COMMITS=$(git log --oneline --pretty=format:"- %s" $LAST_TAG..HEAD 2>/dev/null || echo "")
          else
            COMMITS=$(git log --oneline --pretty=format:"- %s" -10)
          fi

          cat > release_notes.md << EOF
          ## What's New

          $CHANGELOG_SECTION

          ## Recent Commits

          $COMMITS

          ## Installation

          ### Quick Install (Linux/macOS)
          \`\`\`bash
          curl -sSL https://raw.githubusercontent.com/cuesoftinc/open-source-project-generator/main/scripts/install.sh | bash
          \`\`\`

          ### Manual Installation
          1. Download the appropriate archive for your platform
          2. Extract the archive
          3. Follow the installation instructions in the INSTALL.txt file

          ### Package Managers
          - **Debian/Ubuntu**: Download the .deb package and install with \`dpkg -i\`
          - **Red Hat/CentOS**: Download the .rpm package and install with \`rpm -i\`
          - **Homebrew**: \`brew install generator\` (coming soon)

          ## Usage

          \`\`\`bash
          # Generate a new project interactively
          generator generate

          # Show help
          generator --help

          # Validate a generated project
          generator validate ./my-project

          # Show version and latest package versions
          generator version --packages
          \`\`\`

          ## Checksums

          See checksums.txt for SHA256 hashes of all release assets.
          EOF

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body_path: release_notes.md
          files: |
            release-assets/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Notify Release
    runs-on: ubuntu-latest
    needs: [release]
    if: always() && (startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch')

    steps:
      - name: Get version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Notify success
        if: needs.release.result == 'success'
        run: |
          echo "✅ Release ${{ steps.version.outputs.version }} completed successfully!"
          echo "🚀 Binaries and packages are now available"
          echo "📦 Docker image will be built separately by the Docker workflow"

      - name: Notify failure
        if: needs.release.result == 'failure'
        run: |
          echo "❌ Release ${{ steps.version.outputs.version }} failed"
          echo "Check the workflow logs for details"
          exit 1
